version: "3.5"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - "5001:5001"
    
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - /events_app/database.db